---
title: 'Ethics'
pagetitle: 'Your Name'
output: 
  html_document: 
    css: "styles.css"
---
Our project has focused on the preservation and conservation of a population of salamanders unique to Austin - giving our research project distinct ethical implications surrounding continuity and openness, and sustainability. 
As mentioned by Professor Pepita Barnard, one of the most crucial questions to explore when reflecting on the ethical consequences of a field of questioning, especially in nature, is not only how surrounding communities are affected by the research we do, but also how the plants and animals which make up this ecosystem, will be affected. Since the Barton Spring salamanders are an ‘at-risk’ species, the datasets available to us were collected for the sole purpose of preservation and conservation of these animals. Since they are so unique to Austin, native ‘Austinites’ have a sense of kinship to them and loyalty to ensure they remain protected and such data contributed to future efforts in making sure the salamander population at the spring is healthy and thriving. So, even if the primary goal of this data collection was to ensure salamanders have an ideal flow rate and Dissolved Oxygen (DO) level to thrive in, how does this affect other animals in the springs - and what about communities in the surrounding areas?
On average, $40,000 gets set aside for conservation (with proposal funds allocating about $10,000-$80,000 based on the request) and since Barton Springs itself is state-owned land, the land surrounding Barton Springs is inherently more expensive as well. As funding increases for Barton Springs, so does the upkeep and as a result,the property values of the surrounding area increases, leading to a conflict of interest for people who have been living there for so long, now unable to remain in the area because of these high prices. The continued need to fund the conservation of salamanders contributes to the preservation of an endangered species, in turn bolstering the biodiversity of the area and ensuring the ecosystem of Barton Springs remains in balance, however, it begs the question of the city’s prioritizations in the bigger picture of dehousing a sect of the population who now cannot afford to live near such reserves. 
In the vein of public living and opinion, as aforementioned, people living in Austin have loyalty to the salamanders which opens a conversation into the ethical implications of maintaining an open dialogue with the public on conservation efforts. In our experience fortunately, our data was publicly accessible and all of the necessary information was shared about the salamanders and their conservation efforts. However, the data was extremely inaccessible from a layman’s perspective and it was clear that prior academic knowledge and experience in research was needed to understand the data and associated variables. Critically analyzing untidy data has ethical implications in terms of openness towards the public because of methodology changes observed over time. When examining our dataset, it was clear that not only was this data collected over an extremely long period of time, the methods of collecting data had changed over time as well, though the methods weren’t specified and the external effects of changing methods were not considered either. However, the ethical implications of our own project contributes to the increased accessibility of this data as making connections between the various variables and allowing for the public to clearly see the impact of Barton Springs’ unique makeup on the growth of its native salamanders can help future policymakers on their conservation efforts. 
The ethical implications of an untidy dataset concerning the use of the dataset for research is that we don’t know whether changing the method of data collection has affected the actual data itself and therefore the actual accuracy of the observed data. If the data is being used to determine whether salamanders are still an at-risk species in need of public funding, it is incredibly important to have the right data so that the right amount of funds are allocated to such efforts, and the salamanders can be best protected. 
For the most part, since our data collection and hypothesis is concerned with sustainability and conservation, our ethical concerns and analyses revolve around making sure that the data we analyze is able to accurately determine how salamanders are able to thrive in their natural environment, and how the public which interacts with this environment can ensure the longevity of these efforts and contribute to it as well. 

